creative_mode = false
menu_last_game = luanti_edu
mainmenu_last_selected_world = 1
enable_damage = true
server_announce = false
screen_w = 1920
screen_h = 1057
window_maximized = true
maintab_LAST = local
free_move = false
educator_mode = true
name = mani
address = localhost
remote_port = 30000
enable_fog = false
enable_server = false
port = 30000
default_privs = interact, shout
initial_privs = interact, shout
server_dedicated = false
